using UnityEngine;
using UnityEngine.SceneManagement;

public class Bootstrap : MonoBehaviour
{
    // Start is called once before the first execution of Update after the MonoBehaviour is created
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {

    }
    
    void Awake()
    {
         Scene systemScene = SceneManager.GetActiveScene();

        // Kiá»ƒm tra xem hiá»‡n táº¡i chá»‰ cÃ³ duy nháº¥t scene System Ä‘ang má»Ÿ
        if (SceneManager.sceneCount == 1 && systemScene.name == "System")
        {
            Debug.Log("ðŸŸ¢ Only System scene active â†’ Loading MainMenu additively...");
            DontDestroyOnLoad(gameObject);
            SceneManager.LoadSceneAsync("MenuScene", LoadSceneMode.Additive).completed += (op) =>
            {
                SceneManager.SetActiveScene(SceneManager.GetSceneByName("MenuScene"));
            };
        }
        else
        {
            Debug.Log("ðŸŸ¡ System scene already active, keeping persistent objects only");
        }
    }
}
